services:
  
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1499:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=db123@123"
    volumes:
      - "my-sqldb:/var/opt/mssql"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  my-sqldb: